FROM puckel/docker-airflow:1.10.9
RUN pip install requests
RUN pip install opencv-python-headless
RUN pip install pymongo
RUN pip install python-dotenv
RUN pip install ping3
RUN pip install httpx
RUN pip install beautifulsoup4
